doanNet/Controllers/TrangChuController.cs
using doanNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace doanNet.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: Home
        KTXTDTUEntities2 db = new KTXTDTUEntities2();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Gioithieu()
        {
            return View();
        }
        public ActionResult HoatDong()
        {
            var CategoryBridge = db.CategoryBridges.ToList();
            ViewBag.CategoryBridge = CategoryBridge;
            var Post = db.Posts.ToList();   
            ViewBag.Post = Post;
            return View();
        }   
        public ActionResult ThongBao()
        {
            var CategoryBridge = db.CategoryBridges.ToList();
            ViewBag.CategoryBridge = CategoryBridge;
            var Post = db.Posts.ToList();
            ViewBag.Post = Post;
            return View();
        }
        public ActionResult HuongDan()
        {
            return View();
        }
        public ActionResult TinTuc()
        {
            var CategoryBridge = db.CategoryBridges.ToList();
            ViewBag.CategoryBridge = CategoryBridge;
            var Post = db.Posts.ToList();
            ViewBag.Post = Post;
            return View();
        }
        public ActionResult NoiQuy()
        {
            var CategoryBridge = db.CategoryBridges.ToList();
            ViewBag.CategoryBridge = CategoryBridge;
            var Post = db.Posts.ToList();
            ViewBag.Post = Post;
       
            return View();
        }
        public ActionResult ChiTietBaiDang(String Meta)
        {
            var posts = db.Posts.Where(post => post.Meta == Meta).ToList();
            ViewBag.Posts = posts;
            var categoryBridges = db.CategoryBridges.ToList();
            ViewBag.categoryBridges = categoryBridges;
            var Category = db.Categories.ToList();
            ViewBag.Category = Category;
            var allPosts = db.Posts.ToList();
            ViewBag.allPosts = allPosts;

            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        public ActionResult DangNhapGiaoVien()
        {
            return View();
        }
        public ActionResult DangNhapSinhVien()
        {
            return View();
        }
        public ActionResult DoiMatKhau()
        {
            return View();
        }
    }
}

doanNet/Views/TrangChu/ChiTietBaiDang.cshtml
@{
    ViewBag.Title = "ChiTietBaiDang";
    Layout = "~/Views/Shared/layout.cshtml";
}
<link href="~/Content/css/Trangchu.css" rel="stylesheet" />

<style>

    .post-tiltle {
        font-size: 22px;
    }

    .container {
        font-size: 12px;
        padding: 20px;
    }

    .post-created {
        font-size: 70%;
        font-style: italic;
        color: #ccc;
    }
</style>

@{
    var posts = ViewBag.Posts as List<doanNet.Models.Post>;
    @functions {
        // Define the getOppositeColor function
        string GetOppositeColor(string hexColor)
        {
            // Remove '#' if present
            hexColor = hexColor.Replace("#", "");

            // Convert hex to RGB
            int r = Convert.ToInt32(hexColor.Substring(0, 2), 16);
            int g = Convert.ToInt32(hexColor.Substring(2, 2), 16);
            int b = Convert.ToInt32(hexColor.Substring(4, 2), 16);

            // Calculate relative luminance (brightness)
            double luminance = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;

            // Determine contrasting color based on luminance threshold
            return luminance > 0.5 ? "#000000" : "#FFFFFF";
        }
    }
}

@if (posts != null)
{
    foreach (var post in posts)
    {
        List<int> categories = new List<int>();
        List<string> categoriesName = new List<string>();
        HashSet<int> postRelated = new HashSet<int>();

        // Extracting date and time parts
        string datePart = post.DateBegin.ToShortDateString(); // Date part
        string timePart = post.DateBegin.ToShortTimeString(); // Time part
        <div class="container">
            <div class="row" style="padding-top: 50px">
                <h1 class="fw-bold post-tiltle">@post.PostTitle</h1>
                <div class="post-meta">
                    <span class="post-created">TDTU, @datePart | @timePart, GMT+7 </span>
                    <div class="row">
                        @foreach (var categorybridge in ViewBag.categoryBridges)
                        {

                            if (categorybridge.IDPost == post.IDPost)
                            {
                                categories.Add(categorybridge.IDCategory);
                            }
                        }

                        <ul class="category-list" style="display: flex; flex-wrap: nowrap; padding: 0; margin: 0; list-style-type: none;">
                            @foreach (var category in ViewBag.Category)
                            {
                                foreach (int id in categories)
                                {
                                    if (category.IDCategory == id)
                                    {
                                        var oppositeColorForText = GetOppositeColor(category.ColorChip);
                                        <li class="category-checkbox-parents" style="text-decoration:none;display:flex;align-items:center;margin:2px 0; flex-shrink: 0;">
                                            <span class="badge badge-pill badge-primary" style="color: @(oppositeColorForText); margin-left:12px;background-color: @category.ColorChip;" id="@category.IDCategory">@category.CategoryTitle</span>
                                        </li>
                                    }
                                }
                            }
                        </ul>
                    </div>
                    <hr class="border-2 border-dark" />
                </div>
                @Html.Raw(post.PostDetail)


            </div>

            @foreach (var p in ViewBag.categoryBridges)
            {
                foreach (int id in categories)
                {

                    if (id == p.IDCategory && p.IDPost != post.IDPost)
                    {
                        postRelated.Add(p.IDPost); // Add unique IDs to the HashSet
                    }
                }
            }
            <div class="row" style="padding: 50px 50px 50px 0px">
                <h2>BÀI VIẾT LIÊN QUAN</h2>
                <hr style="border-top: 4px solid blue;">
            </div>


            <div class="card-container">
                @foreach (var p in ViewBag.allPosts)
                {
                    var i = 0;
                    foreach (int id in postRelated)
                    {
                        if (id == p.IDPost)
                        {
                            <div class="col-xs-12 col-sm-4">
                                <div class="card">
                                    <a class="img-card" href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = p.Meta })">
                                        <img src="~/Content/upload/img/news/@p.PostImage" />
                                    </a>
                                    <div class="card-content">
                                        <h4 class="card-title">
                                            <a href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = p.Meta })">
                                                @post.PostTitle
                                            </a>
                                        </h4>
                                        <div id="someDiv">
                                            <p class="">
                                                @Html.Raw(p.PostDetail)
                                            </p>
                                        </div>

                                    </div>
                                    <div class="card-read-more">
                                        <a href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = p.Meta })" class="btn btn-link btn-block">
                                            <!-- Link content -->
                                            Read More
                                        </a>
                                    </div>
                                </div>
                            </div>
                            i++;
                        }
                    }
                }
            </div>

        </div>

    }

}
else
{
    <p>No posts found.</p>
}

doanNet/Views/TrangChu/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/layout3.cshtml";
}
<style>
    .container-login {
        cursor: pointer;
        display: flex;
        align-items: center;
        max-width: 600px;
        margin: 20px auto;
        padding: 10px 20px 10px 20px;
        border: 1px solid none;
        border-radius: 0px;
        background-color: deepskyblue
    }

    .image-container {
        flex-shrink: 0;
        margin-right: 20px;
        border: 3px solid none;
        border-radius: 10px;
        background-color: white;
        padding: 10px 20px 10px 20px;
    }

        .image-container img {
            max-width: 100%;
            height: auto;
            display: block;
        }

    .text-container {
        flex-grow: 1;
        color: white;
        font-weight: bold;
        padding: 10px;
    }
    .next-button {
        float: left;
        bottom: 20px;
        right: 20px;
        background-color: darkblue;
        color: white;
        font-weight: bold;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }
</style>
<div class="container-fluid">
    <div style="padding: 20px; background-color: darkblue; color: white; font-weight: bold">Đăng nhập ký túc xá</div>
    <div class="container" style=" max-width: 600px; ">
        <div class="container-login" onclick="location.href='@Url.Action("DangNhapGiaoVien", "TrangChu")';">
            <div class="image-container">
                <img src="~/Images/teacher.png" style="width:64px; height:auto">
            </div>
            <div class="text-container">
                <p>Đăng nhập qua tài khoản Cán bộ</p>
            </div>
        </div>

        <div class="container-login" onclick="location.href='@Url.Action("DangNhapSinhVien", "TrangChu")';">
            <div class="image-container">
                <img src="~/Images/student.png">
            </div>
            <div class="text-container">
                <p>Đăng nhập qua tài khoản Sinh viên</p>
            </div>
        </div>
        <a href="/TrangChu" class="btn next-button"><i class="fa-solid fa-arrow-left" style="padding-right: 20px"></i>Trang chủ</a>
    </div>
</div>

doanNet/Views/TrangChu/DangNhapGiaoVien.cshtml
@{
    ViewBag.Title = "DangNhapGiaoVien";
    Layout = "~/Views/Shared/layout3.cshtml";
}

<style>
    body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }

    .corner-image {
        padding-top: 10px;
        padding-right: 50px;
        position: absolute;
        top: 0;
        right: 0;
    }

    a {
        text-decoration: none;
    }

    .login-page {
        width: 100%;
        padding-top: 50px;
        display: inline-block;
        display: flex;
        align-items: center;
    }

    .form-right i {
        font-size: 100px;
    }
</style>


<div class="container-fluid" style="background-color: darkblue; height:150px">
    <h1 style="font-weight: bold; color: white; text-align: center; padding-top: 50px;">Đăng nhập</h1>
    <img src="~/Images/teacher.png" class="corner-image">
</div>

@Scripts.Render("~/Areas/admin/Content/Script/JSAPI/AccountAPI.js")
<section class="vh-90">
    <div class="container py-5 h-100">
        <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
                     class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">

                <!-- Email input -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="form1Example13">MSGV</label>
                    <input type="text" id="form1Example13" class="form-control form-control-lg mssv_place" />

                </div>

                <!-- Password input -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="form1Example23">Mật khẩu</label>
                    <input type="password" id="form1Example23" class="form-control form-control-lg password_place" />
                </div>

                <div class="d-flex justify-content-around align-items-center mb-4">

                    <a href="TrangChu/DoiMatKhau!">Quên mật khẩu?</a>
                </div>

                <!-- Submit button -->
                <div class="row">
                    <div class="col-6">
                        <a href="/TrangChu/DangNhap/"><i class="fa-solid fa-arrow-left" style="padding-right: 10px"></i>Trở về</a>
                    </div>
                    <div class="col-6">
                        <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg btn-block btn_login float-end">Đăng nhập</button>

                    </div>
                </div>
                <script>
                    $(document).ready(() => {
                        $(".btn_login").click(async () => {
                            const loginData = {
                                account: $(".mssv_place").val(),
                                password: $(".password_place").val(),
                            }
                            let response = await CheckingLogin(loginData);
                            if (response.status == 200) {
                                const AccountDetail = await response.json();

                                if (AccountDetail) {
                                    sessionStorage.setItem("IDAccount", AccountDetail.IDAccount)
                                    if (AccountDetail.AccountTypeID == 4) {
                                        window.location.href = "/GiaoVien/QuanLy/Loi"
                                    }

                                }
                            }
                            else {
                                alert("Đăng nhập thất bại")
                            }
                        })
                    })

                </script>
            </div>
        </div>
    </div>
</section>

doanNet/Views/TrangChu/DangNhapSinhVien.cshtml
@{
    ViewBag.Title = "DangNhapSinhVien";
    Layout = "~/Views/Shared/layout3.cshtml";
}
@using System.Web.Optimization
@Scripts.Render("~/Areas/admin/Content/Script/JSAPI/AccountAPI.js")
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }

    .corner-image {
        padding-top: 10px;
        padding-right: 50px;
        position: absolute;
        top: 0;
        right: 0;
    }

    a {
        text-decoration: none;
    }

    .login-page {
        width: 100%;
        padding-top: 50px;
        display: inline-block;
        display: flex;
        align-items: center;
    }

    
    .divider:after,
    .divider:before {
        content: "";
        flex: 1;
        height: 1px;
        background: #eee;
    }
</style>


<div class="container-fluid" style="background-color: darkblue; height:150px">
    <h1 style="font-weight: bold; color: white; text-align: center; padding-top: 50px;">Đăng nhập</h1>
    <img src="~/Images/graduates.png" class="corner-image">
</div>
<section class="vh-90">
    <div class="container py-5 h-100">
        <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
                     class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">

                <!-- Email input -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="form1Example13">MSSV</label>
                    <input type="text" id="form1Example13" class="form-control form-control-lg mssv_place" />

                </div>

                <!-- Password input -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="form1Example23">Mật khẩu</label>
                    <input type="password" id="form1Example23" class="form-control form-control-lg password_place" />
                </div>

                <div class="d-flex justify-content-around align-items-center mb-4">

                    <a href="TrangChu/DoiMatKhau!">Quên mật khẩu?</a>
                </div>

                <!-- Submit button -->
                <div class="row">
                    <div class="col-6">
                        <a href="/TrangChu/DangNhap/"><i class="fa-solid fa-arrow-left" style="padding-right: 10px"></i>Trở về</a>
                    </div>
                    <div class="col-6">
                        <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg btn-block btn_login float-end">Đăng nhập</button>

                    </div>
                </div>


                <script>
                     $(document).ready(() => {
                         $(".btn_login").click(async () => {
                             const loginData = {
                                 account: $(".mssv_place").val(),
                                 password: $(".password_place").val(),
                             }
                             let response = await CheckingLogin(loginData);
                             if (response.status == 200) {
                                 const AccountDetail = await response.json();
                                 if (AccountDetail.Hide == 1) {
                                     alert("Tài khoản sinh viên đã bị khóa");
                                     return;
                                 }
                                 if (AccountDetail) {
                                     sessionStorage.setItem("IDAccount", AccountDetail.IDAccount)
                                     sessionStorage.setItem("AccountTypeID", AccountDetail.AccountTypeID)

                                     if (AccountDetail.Available == 0) {
                                         window.location.href = "@Url.Action("DoiMatKhau", "TrangChu")"
                                     }
                                     else {
                                          if (AccountDetail.AccountTypeID == 6) {
                                             window.location.href="@Url.Action("Loi", "SinhVien")"
                                         }
                                         if (AccountDetail.AccountTypeID == 5) {
                                             window.location.href="/SinhVienTuQuan/Default/DiemDanhKTX"
                                         }
                                     }

                                 }
                             }
                             else {
                                 alert("Đăng nhập thất bại")
                             }
                     })
                     })

                </script>
            </div>
        </div>
    </div>
</section>

doanNet/Views/TrangChu/HoatDong.cshtml
@{
    ViewBag.Title = "HoatDong";
    Layout = "~/Views/Shared/layout.cshtml";
}
<link href="~/Content/css/Trangchu.css" rel="stylesheet" />

<div class="container">
    <div class="row" style="padding: 50px 50px 50px 0px">
        <h2>HOẠT ĐỘNG PHONG TRÀO</h2>
        <hr style="border-top: 4px solid blue;">
    </div>

    @{
        var idPostList = new List<int>();

        foreach (var item in ViewBag.CategoryBridge)
        {
            if (item.IDCategory == 2)
            {
                idPostList.Add(item.IDPost);
            }
        }
    }
    @if (idPostList.Any())
    {
        for (int i = 0; i < idPostList.Count; i += 3)
        {
            <div class="container">
                <div class="row">
                    @for (int j = i; j < Math.Min(i + 3, idPostList.Count); j++)
                    {
                        foreach (var post in ViewBag.Post)
                        {
                            if (@idPostList[j] == post.IDPost)
                            {
                                <div class="col-xs-12 col-sm-4">
                                    <div class="card">
                                        <a class="img-card" href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = post.Meta })">
                                            <img src="~/Content/upload/img/news/@post.PostImage" />
                                        </a>
                                        <div class="card-content">
                                            <h4 class="card-title">
                                                <a href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = post.Meta })">
                                                    @post.PostTitle
                                                </a>
                                            </h4>
                                            <div id="someDiv">
                                                <p class="">

                                                    @Html.Raw(post.PostDetail)
                                                </p>
                                            </div>

                                        </div>
                                        <div class="card-read-more">
                                            <a href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = post.Meta })" class="btn btn-link btn-block">
                                                <!-- Link content -->
                                                Read More
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            }
                        }

                    }
                </div>
            </div>
        }
    }

  
</div>

doanNet/Views/TrangChu/HuongDan.cshtml
@{
    ViewBag.Title = "HuongDan";
    Layout = "~/Views/Shared/layout.cshtml";
}
<style>
    .card {
        transition: box-shadow 0.3s ease;
    }
    .card {
        cursor: pointer;
    }


        .card:hover {
            border: 1px solid #ced4da; /* Gray border color */
            box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.3); /* Elevation effect */
        }

    body, html {
        height: 100%;
        margin: 0;
        padding: 0;
    }

    .container-full {
        min-height: 100%;
        background-color: lightgray;
        padding-bottom: 300px;
    }
</style>


<div class="container-full">
    <div class="container" style="padding-top: 50px; padding-right: 50px; padding-left: 50px;">
        <div class="row">
            <h2>HƯỚNG DẪN</h2>
            <hr style="border-top: 4px solid blue;">
        </div>
        <div class="row row-cols-5 g-4">
            <div class="col">
                <div class="card" style="display: flex; align-items: center; justify-content: center; height: 200px">
                    <img src="~/Images/written-paper.png" class="card-img-top" style="width: 120px; height: 120px; padding: 20px">
                    <div class="card-body">
                        <p class="card-title" style="font-weight: bold; font-size: 15px; padding-bottom: 30px; text-align:center">Đăng ký nội trú</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="display: flex; align-items: center; justify-content: center; height: 200px">
                    <img src="~/Images/parking.png" class="card-img-top" style="width: 120px; height: 120px; padding: 20px">
                    <div class="card-body">
                        <p class="card-title" style="font-weight: bold; font-size: 15px; padding-bottom: 30px; text-align:center">Gửi xe, Đổi xe, Chấm dứt HĐ xe</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="display: flex; align-items: center; justify-content: center; height: 200px">
                    <img src="~/Images/contract.png" class="card-img-top" style="width: 120px; height: 120px; padding: 20px">
                    <div class="card-body">
                        <p class="card-title" style="font-weight: bold; font-size: 15px; padding-bottom: 30px; text-align: center;">Chấm dứt hộp đồng nội trú</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="display: flex; align-items: center; justify-content: center; height: 200px">
                    <img src="~/Images/late.png" class="card-img-top" style="width: 120px; height: 120px; padding: 20px">
                    <div class="card-body">
                        <p class="card-title" style="font-weight: bold; font-size: 15px; padding-bottom: 30px; text-align: center">Xin về trễ sau giờ quy định (22h00)</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="display: flex; align-items: center; justify-content: center; height: 200px">
                    <img src="~/Images/stay-at-home.png" class="card-img-top" style="width: 120px; height: 120px; padding: 20px">
                    <div class="card-body">
                        <p class="card-title" style="font-weight: bold; font-size: 15px; padding-bottom: 30px; text-align: center">Tạm vắng - Tạm trú</p>
                    </div>
                </div>
            </div>
            <!-- Các cột khác -->
        </div>
        </div>


    </div>

doanNet/Views/TrangChu/TinTuc.cshtml
@{
    ViewBag.Title = "TinTuc";
    Layout = "~/Views/Shared/layout.cshtml";
}
<link href="~/Content/css/Trangchu.css" rel="stylesheet" />

<div class="container">
    <div class="row" style="padding: 50px 50px 50px 0px">
        <h2>TIN TỨC</h2>
        <hr style="border-top: 4px solid blue;">
    </div>

    @{
        var idPostList = new List<int>();

        foreach (var item in ViewBag.CategoryBridge)
        {
            if (item.IDCategory == 10)
            {
                idPostList.Add(item.IDPost);
            }
        }
    }
    @if (idPostList.Any())
    {
        for (int i = 0; i < idPostList.Count; i += 3)
        {
            <div class="container">
                <div class="row">
                    @for (int j = i; j < Math.Min(i + 3, idPostList.Count); j++)
                    {
                        foreach (var post in ViewBag.Post)
                        {
                            if (@idPostList[j] == post.IDPost)
                            {
                                <div class="col-xs-12 col-sm-4">
                                    <div class="card">
                                        <a class="img-card" href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = post.Meta })">
                                            <img src="~/Content/upload/img/news/@post.PostImage" />
                                        </a>
                                        <div class="card-content">
                                            <h4 class="card-title">
                                                <a href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = post.Meta })">
                                                    @post.PostTitle
                                                </a>
                                            </h4>
                                            <div id="someDiv">
                                                <p class="">

                                                    @Html.Raw(post.PostDetail)
                                                </p>
                                            </div>

                                        </div>
                                        <div class="card-read-more">
                                            <a href="@Url.Action("ChiTietBaiDang", "TrangChu", new { meta = post.Meta })" class="btn btn-link btn-block">
                                                <!-- Link content -->
                                                Read More
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            }
                        }

                    }
                </div>
            </div>
        }
    }

   
</div>