doanNet/Models/Menu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Order { get; set; }
        public string Meta { get; set; }
        public System.DateTime DateBegin { get; set; }
        public int Hide { get; set; }
        public string TextMenu { get; set; }
        public Nullable<int> FatherID { get; set; }
        public List<Menu> Children { get; internal set; }
    }
}

doanNet/Models/SinhVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanNet.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.Accounts = new HashSet<Account>();
            this.AttendanceBridges = new HashSet<AttendanceBridge>();
            this.Contracts = new HashSet<Contract>();
            this.Logs = new HashSet<Log>();
            this.Mistakes = new HashSet<Mistake>();
        }
    
        public int IDSinhVien { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public System.DateTime BirthDay { get; set; }
        public System.DateTime AttendDate { get; set; }
        public int AttendYear { get; set; }
        public int GraduateYear { get; set; }
        public string MSSV { get; set; }
        public int IDFalcuty { get; set; }
        public int IDRoom { get; set; }
        public Nullable<int> Order { get; set; }
        public string Meta { get; set; }
        public System.DateTime DateBegin { get; set; }
        public int Hide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<AttendanceBridge> AttendanceBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Contract> Contracts { get; set; }
        
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Log> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Mistake> Mistakes { get; set; }
        public virtual Room Room { get; set; }
    }
}

doanNet/Areas/GiaoVien/Controllers/MenuController.cs
using doanNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace doanNet.Areas.GiaoVien.Controllers
{
    public class MenuController : Controller
    {
        // GET: GiaoVien/Menu
        public ActionResult Index()
        {
            return View();
        }
      
        // GET: Menu
        KTXTDTUEntities2 _db = new KTXTDTUEntities2();

  
        public PartialViewResult GenerateMenu2()
        {
            var menuItems = _db.Menus.ToList();
            ViewBag.MenuItems = menuItems.ToArray();

            // Thực hiện các xử lý khác nếu cần
            return PartialView("GenerateMenu2");
        }
        
    }
}

doanNet/Areas/GiaoVien/Controllers/QuanLyController.cs
    using doanNet.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace doanNet.Areas.GiaoVien.Controllers
{
    public class QuanLyController : Controller
    {
        KTXTDTUEntities2 db = new KTXTDTUEntities2();
        // GET: GiaoVien/Default
        public ActionResult ChoosingRoom()
        {
            var rooms = db.Rooms.ToList();
            var ArrNumOfStudent = new List<int>();
            foreach (var room in rooms)
            {
                int NumberStudentOfRoom = db.SinhViens.Where(row => row.IDRoom == room.IDRoom).Count(); ;
                ArrNumOfStudent.Add(NumberStudentOfRoom);
            }
            ViewBag.ArrNumOfStudent = ArrNumOfStudent;
            ViewBag.rooms = rooms;
            return View();
        }
        public ActionResult SinhVien()
        {
            var sinhviens = db.SinhViens.ToList();
            var falcuties = db.Faculties.ToList();
            ViewBag.falcuties = falcuties;
            ViewBag.sinhviens=sinhviens;
            var rooms = db.Rooms.ToList();
            ViewBag.rooms = rooms;
            return View();
        }
        public ActionResult DanhSachHopDong()
        {
            var contracts = db.Contracts.ToList();
            ViewBag.contracts=contracts;

            var places = db.Places.ToList();
            ViewBag.places=places;

            var priorities = db.Priorities.ToList();
            ViewBag.priorities=priorities;

            var sinhviens = db.SinhViens.ToList();
            ViewBag.sinhviens= sinhviens;

            return View();
        }
        public ActionResult DanhSachHoaDon()
        {
            var Fees = db.Fees.ToList();
            ViewBag.Fees = Fees;

            var places = db.Places.ToList();
            ViewBag.places = places;

            var rooms = db.Rooms.ToList();
            ViewBag.rooms = rooms;

            var priorities = db.Priorities.ToList();
            ViewBag.priorities = priorities;

            var sinhviens = db.SinhViens.ToList();
            ViewBag.sinhviens = sinhviens;

            return View();
        }
        public ActionResult DanhSachHoaDonTheoThang(int Year,int Month)
        {

            var allFloor = db.Rooms
                            .Select(e => e.Floor)
                            .Distinct()
                            .ToList();
            ViewBag.allFloor = allFloor;
            var Fees = db.Fees.Where(fee => fee.DateStart.Year == Year && fee.DateStart.Month== Month).ToList();
            ViewBag.Fees = Fees;

            var rooms = db.Rooms.ToList();
            ViewBag.rooms = rooms;

            var priorities = db.Priorities.ToList();
            ViewBag.priorities = priorities;

            var sinhviens = db.SinhViens.ToList();
            ViewBag.sinhviens = sinhviens;
            return View();
        }
        public ActionResult GhiLoiKTX()
        {
            return View();
        }
        public ActionResult Loi()
        {
            var mistake = db.Mistakes.ToList();
            ViewBag.mistakes=mistake;

            var sinhvien = db.SinhViens.ToList();
            ViewBag.sinhviens = sinhvien;

            var rooms = db.Rooms.ToList();
            ViewBag.rooms=rooms;
            return View();
        }
        public ActionResult BaiViet()
        {
            var posts = db.Posts.ToList();
            ViewBag.posts=posts;

            var categogries = db.Categories.ToList();
            ViewBag.categories = categogries;
            
            var categorybridge = db.CategoryBridges.ToList();
            ViewBag.categoryBridges = categorybridge;
            return View();
        }
        public ActionResult ReloadPost()
        {
            return RedirectToAction("BaiViet");
        }
        public ActionResult Menu()
        {
            var Menus = db.Menus.ToList();
            ViewBag.Menus = Menus;
            return View();
        }
        public ActionResult Phong(string tang) { 
            var rooms = db.Rooms.ToList();
            ViewBag.rooms = rooms;

            if (tang == null)
            {
                var allFloor = db.Rooms
                             .Select(e => e.Floor)
                             .Distinct()
                             .ToList();
                var allFloor2 = db.Rooms
                           .Select(e => e.Building)
                           .Distinct()
                           .ToList();
                var RoomList = db.Rooms.ToList();
                var SinhVienList = db.SinhViens.ToList();
                ViewBag.RoomList = RoomList;
                ViewBag.SinhVienList = SinhVienList;
                ViewBag.allFloor = allFloor;
                ViewBag.allFloor2 = allFloor2;
                return View();
            }
            else
            {
                var allFloor = db.Rooms
                            .Select(e => e.Floor)
                            .Distinct()
                            .ToList();
                var allFloor2 = db.Rooms
                            .Select(e => e.Building)
                            .Distinct()
                            .ToList();
                var tangNum = Int32.Parse(tang);
                var RoomList = db.Rooms.Where(row => row.Floor == tangNum).ToList();
                var SinhVienList = db.SinhViens.ToList();
                ViewBag.RoomList = RoomList;
                ViewBag.SinhVienList = SinhVienList;
                ViewBag.allFloor = allFloor;
                ViewBag.allFloor2 = allFloor2;
            }

            return View();
        }
        public ActionResult TaiKhoan()
        {
            var sinhviens = db.SinhViens.ToList();
            var Account = db.Accounts.Where(row=>row.AccountTypeID!=4).ToList();

            var falcuties = db.Faculties.ToList();
            ViewBag.falcuties = falcuties;
            ViewBag.sinhviens = sinhviens;
            var AccountType = db.AccountTypes.ToList();
            ViewBag.AccountType = AccountType;
            ViewBag.Account = Account;

            return View();
        }
        public ActionResult ThemBaiViet()
        {
            return View();
        }
        public ActionResult SuaLoiKTX(int id)
        {
            var MistakeInfo = db.Mistakes.Where(row => id == row.IDMistake).FirstOrDefault();
            var SinhVienID = MistakeInfo.IDSinhVien;
            var SinhVienInfo = db.SinhViens.Where(row=> SinhVienID==row.IDSinhVien).FirstOrDefault();
            var RoomInfo= db.Rooms.Where(row=>row.IDRoom==MistakeInfo.IDRoom).FirstOrDefault();
            ViewBag.FileInfo = MistakeInfo.ImageDescription;

            ViewBag.SinhVienInfo = SinhVienInfo;
            ViewBag.MistakeInfo = MistakeInfo;
            ViewBag.RoomInfo = RoomInfo;

            return View();
        }
        public ActionResult SuaBaiViet(int id)
        {
            var PostInfo = db.Posts.Where(row => id == row.IDPost).FirstOrDefault();
            var CategoryInfo = db.CategoryBridges.Where(row=>row.IDPost==id).Select(e=> e.IDCategory).ToList();

            ViewBag.CategoryInfo = CategoryInfo;
            ViewBag.PostInfo = PostInfo;

            return View();
        }
    }
}

doanNet/Areas/SinhVienTuQuan/Controllers/MenuController.cs
using doanNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace doanNet.Areas.SinhVienTuQuan.Controllers
{
    public class MenuController : Controller
    {
        // GET: SinhVienTuQuan/Menu
        public ActionResult Index()
        {
            return View();
        }

        // GET: Menu
        KTXTDTUEntities2 _db = new KTXTDTUEntities2();


        public PartialViewResult GenerateMenu2()
        {
            var menuItems = _db.Menus.ToList();
            ViewBag.MenuItems = menuItems.ToArray();

            // Thực hiện các xử lý khác nếu cần
            return PartialView("GenerateMenu2");
        }

    }

}

doanNet/Controllers/MenuController.cs
using doanNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace doanNet.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
       KTXTDTUEntities2 _db = new KTXTDTUEntities2();

        public ActionResult GenerateMenu()
        {
            var menuItems = _db.Menus.ToList();
            ViewBag.MenuItems = menuItems.ToArray();
            // Thực hiện các xử lý khác nếu cần
            return PartialView("GenerateMenu");
        }

           public PartialViewResult GenerateMenu2()
           {
               var menuItems = _db.Menus.ToList();
            ViewBag.MenuItems = menuItems.ToArray();

            // Thực hiện các xử lý khác nếu cần
            return PartialView("GenerateMenu2");
           }

           public PartialViewResult GenerateMenu3()
           {
               var menuList = _db.Menus.ToList();
            ViewBag.MenuItems = menuList;
            // Thực hiện các xử lý khác nếu cần
            return PartialView("GenerateMenu3");
           }

    }
}

doanNet/Controllers/SinhVienController.cs
using doanNet.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace doanNet.Controllers
{
    public class SinhVienController : Controller
    {
        // GET: Student

        KTXTDTUEntities2 db = new KTXTDTUEntities2();


        public ActionResult TrangChu()
        {
            return View();
        }
        public ActionResult DangKyKyTucXa()
        {
            return View();
        }
        public ActionResult DanhSachHopDong()
        {
            return View();
        }
        public ActionResult Loi()
        {
            return View();
        }
        public ActionResult DanhSachHoaDonTheoThang()
        {

            var allFloor = db.Rooms
                            .Select(e => e.Floor)
                            .Distinct()
                            .ToList();
            ViewBag.allFloor = allFloor;
            var Fees = db.Fees.ToList();
            ViewBag.Fees = Fees;

            var rooms = db.Rooms.ToList();
            ViewBag.rooms = rooms;

            var priorities = db.Priorities.ToList();
            ViewBag.priorities = priorities;

            var sinhviens = db.SinhViens.ToList();
            ViewBag.sinhviens = sinhviens;
            return View();
        }
     
    }
}

doanNet/Areas/GiaoVien/Views/QuanLy/BaiViet.cshtml
@{
    ViewBag.Title = "Bài Viết";
    Layout = "~/Views/Shared/layoutteacher.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-12 text-center" style="padding:20px">
            <h2 style="font-weight: bold">DANH SÁCH BÀI VIẾT</h2>
        </div>
    </div>
    <div class="filtering_place">
        <input type="date" class="date_filtering_place" />
    </div>
    <div class="function_btn" style="display: flex; justify-content: end; margin-top: 8px; margin-bottom: 8px; margin-right: 32px;">
        <div class="add_btn" style="margin: 10px">
            <!-- Colored mini FAB button -->
            <button class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored"
                    style="background-color: #35d66c">
                <a href="@Url.Action("ThemBaiViet","QuanLy")">
                    <i class="fa-solid fa-plus" style="margin: 10px"></i>
                </a>
            </button>

        </div>
    </div>
    <script>
        $(document).ready(() => {

        })
    </script>
    <div class="row">
        <table class="table" id="datatableform">
            <thead>
                <tr style="background-color: darkblue; color: white">
                    <th scope="col">Tiêu đề</th>
                    <th scope="col">Meta</th>
                    <th scope="col">Lần cuối chỉnh sửa</th>
                    <th scope="col">Tag bài đăng</th>
                    <th scope="col">Thao tác</th>
                </tr>
            </thead>
            <tbody>
                @functions {
                    // Define the getOppositeColor function
                    string GetOppositeColor(string hexColor)
                    {
                        // Remove '#' if present
                        hexColor = hexColor.Replace("#", "");

                        // Convert hex to RGB
                        int r = Convert.ToInt32(hexColor.Substring(0, 2), 16);
                        int g = Convert.ToInt32(hexColor.Substring(2, 2), 16);
                        int b = Convert.ToInt32(hexColor.Substring(4, 2), 16);

                        // Calculate relative luminance (brightness)
                        double luminance = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;

                        // Determine contrasting color based on luminance threshold
                        return luminance > 0.5 ? "#000000" : "#FFFFFF";
                    }
                }
                @functions {
                    // Define the formatDateTime function
                    string formatDateTime(DateTime dateTime)
                    {
                        // Implement your logic here to format the datetime string
                        // For example:

                        return dateTime.ToString("dd/MM/yyyy");
                    }
                }
                @foreach (var item in ViewBag.posts)
                {
                    List<int> categories = new List<int>();
                    List<string> categoriesName = new List<string>();
                    <tr>
                        <th>@item.PostTitle</th>
                        <td>@item.Meta</td>
                        <td>@formatDateTime(item.DateBegin)</td>
                        <td>
                            @foreach (var categorybridge in ViewBag.categoryBridges)
                            {
                                if (categorybridge.IDPost == item.IDPost)
                                {
                                    categories.Add(categorybridge.IDCategory);
                                }
                            }
                            @foreach (var category in ViewBag.Categories)
                            {
                                foreach (int id in categories)
                                {
                                    if (category.IDCategory == id)
                                    {
                                        var oppositeColorForText = GetOppositeColor(category.ColorChip);
                                        <li class="category-checkbox-parents" style="text-decoration:none;display:flex;align-items:center;margin:4px 0">
                                            <span class="badge badge-pill badge-primary" style="color: @(oppositeColorForText); margin-left:12px;background-color: @category.ColorChip;" id="@category.IDCategory">@category.CategoryTitle</span>
                                        </li>
                                    }
                                }
                            }
                        </td>
                        <td>
                            <a href="@Url.Action("SuaBaiViet", "QuanLy", new {id = @item.IDPost})">
                                <i class="fa-regular fa-pen-to-square" style="color: blue;"></i>
                            </a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>
<script>
    $('.date_filtering_place').on('change', function (e) {
        var dateVal = $(this).val();
        var regex = /\b(\d{4})-(\d{2})-(\d{2})\b/;

        // Check if the dateVal matches the regex pattern
        var match = dateVal.match(regex);

        if (match) {
            // Extract year, month, and day from the matched groups
            var year = match[1];
            var month = match[2];
            var day = match[3];

            // Construct the new date string in the DD-MM-YYYY format
            var newDateString = day + "/" + month + "/" + year;

        } else {
            console.log("Invalid date format.");
        }
        //dataTable.column(6).search('\\s' + status + '\\s', true, false, true).draw();
        table.column(2).search(newDateString, true, false).draw();
    })
</script>

doanNet/Areas/GiaoVien/Views/QuanLy/ChoosingRoom.cshtml
@{
    Layout = "~/Views/Shared/layoutteacher.cshtml";
}

<link href="~/Content/TeacherPage/ChoosingRoom.min.css" rel="stylesheet" />
<div class="filtering_place">
    <select class="filtering_item" placeholder="Tòa">
        <option value="" disabled selected>Tòa</option>
        <option value="hurr">Durr</option>
    </select>
    <select class="filtering_item" placeholder="Tầng">
        <option value="" disabled selected>Tầng</option>
        <option value="hurr">Durr</option>
    </select>
    <select class="filtering_item" placeholder="Loại Phòng">
        <option value="" disabled selected>Loại Phòng</option>
        <option value="hurr">Durr</option>
    </select>
    <select class="filtering_item" placeholder="Trạng thái">
        <option value="" disabled selected>Trạng thái</option>
        <option value="hurr">Durr</option>

    </select>
    <button data-bs-toggle="modal"
            data-bs-target="#ModalChooseCategory"
            class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored"
            style="background-color: #1C63EE;margin:0">
        <i class="fa-solid fa-magnifying-glass"></i>
    </button>
</div>
<div class="choosing_room_place">
    @{var number = 0; }
    @foreach (var item in ViewBag.rooms)
    {
        if (item.RoomType > @ViewBag.ArrNumOfStudent[number])
        {
            <div class="choosing_room_item" id=@item.IDRoom>
                <div class="display_info">
                    <p class="name_of_room"id="@item.Name">Phòng @item.Name</p>
                    <div class="display_side_info_title" style="display:flex">
                        <div class="side_info">
                            <p class="side_heading_place">Tòa</p>
                            <p class="side_content_place">@item.Building</p>
                        </div>
                        <div class="side_info">
                            <p class="side_heading_place">Tầng</p>
                            <p class="side_content_place">@item.Floor</p>
                        </div>
                        <div class="side_info">
                            <p class="side_heading_place">Loại Phòng</p>
                            <p class="side_content_place" >@item.RoomType người</p>
                        </div>
                    </div>
                </div>

                <div class="choosing_room_status">
                    <div class="room_info ">
                        <div class="side_info">
                            <p class="heading_number_tag">Số lượng</p>
                            <p class="number_des">@ViewBag.ArrNumOfStudent[number] <span>/</span> 8</p>
                        </div>
                    </div>
                    <div class="btn_place" style="text-align:center">
                        <button class="btn_choose" id=@item.IDRoom>
                            Chọn
                        </button>
                    </div>

                </div>
            </div>
        }
        else
        {
            <div class="choosing_room_item">
                <div class="display_info">
                    <p class="name_of_room">Phòng @item.Name</p>
                    <div class="display_side_info_title" style="display:flex">
                        <div class="side_info">
                            <p class="side_heading_place">Tòa</p>
                            <p class="side_content_place">@item.Building</p>
                        </div>
                        <div class="side_info">
                            <p class="side_heading_place">Tầng</p>
                            <p class="side_content_place">@item.Floor</p>
                        </div>
                        <div class="side_info">
                            <p class="side_heading_place">Loại Phòng</p>
                            <p class="side_content_place">@item.RoomType người</p>
                        </div>
                    </div>
                </div>

                <div class="choosing_room_status">
                    <div class="room_info not_available">
                        <div class="side_info">
                            <p class="heading_number_tag">Số lượng</p>
                            <p class="number_des">@ViewBag.ArrNumOfStudent[number] <span>/</span> 8</p>
                        </div>
                    </div>
                    <div class="btn_place" style="text-align:center">
                        <button class="btn_choose not_available">
                            Hết chỗ
                        </button>
                    </div>

                </div>
            </div>
        }
        number++;

    }
</div>
<script>
    if (!sessionStorage.getItem("StudentTempData") && !sessionStorage.getItem("StudentTempDataEdit")) {
    const returnhref = '@Url.Action("SinhVien", "QuanLy")';
    window.location.href = returnhref;
    }

         $(".btn_choose").click(function (e){
             e.preventDefault();
                 if (sessionStorage.getItem("StudentTempData")) {
                     if (!$(this).hasClass('not_available')) {
                         const SinhVienData = JSON.parse(sessionStorage.getItem("StudentTempData"))
                         var roomId = $(this).attr('id'); // Retrieve the RoomID from the ID of the button
                         var roomName = $(this).closest('.choosing_room_item').find('.name_of_room').attr("id");
                         SinhVienData.RoomID = roomId;
                         SinhVienData.RoomName = roomName;
                         sessionStorage.setItem("StudentTempData", JSON.stringify(SinhVienData))
                         const returnhref = '@Url.Action("SinhVien", "QuanLy")';
                         window.location.href = returnhref;
                     }
                 }
                 if (sessionStorage.getItem("StudentTempDataEdit")) {
                     if (!$(this).hasClass('not_available')) {
                         const SinhVienData = JSON.parse(sessionStorage.getItem("StudentTempDataEdit"))
                         var roomId = $(this).attr('id'); // Retrieve the RoomID from the ID of the button
                         var roomName = $(this).closest('.choosing_room_item').find('.name_of_room').attr("id");
                         SinhVienData.RoomID = roomId;
                         SinhVienData.RoomName = roomName;
                         sessionStorage.setItem("StudentTempDataEdit", JSON.stringify(SinhVienData))
                         const returnhref = '@Url.Action("SinhVien", "QuanLy")';
                         window.location.href = returnhref;
                     }
                 }
             }
         )
</script>
<div style="text-align:center">
    <nav aria-label="Page navigation example" class="base-pagination">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            <li class="page-item"><a class="page-active page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">...</a></li>
            <li class="page-item"><a class="page-link" href="#">5</a></li>
            <li class="page-item"><a class="page-link" href="#">6</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>
</div>

doanNet/Areas/GiaoVien/Views/QuanLy/Phong.cshtml
@{
    ViewBag.Title = "QuanLyPhong";
    Layout = "~/Views/Shared/layoutteacher.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/Areas/admin/Content/CSS/GiaoVien.css">

<div class="container">
    <div class="col-12 text-center" style="padding:20px">
        <h2 style="font-weight: bold">QUẢN LÝ PHÒNG</h2>
    </div>
    <div class="row">
        <div class="col-1">
            <select name="tang" id="tang">
                <option value="0" disabled selected>Tầng</option>
                @foreach (var Floor in ViewBag.allFloor)
                {

                    <option value="@Floor">Tầng @Floor</option>
                }
            </select>
        </div>
        <div class="col-1">
            <select name="toa" id="toa">
                <option value="0" disabled selected>Toà</option>
                @foreach (var Building in ViewBag.allFloor2)
                {
                    <option value="@Building">Toà @Building</option>
                  
                }
            </select>
        </div>
    </div>
  
  
    <div class="row">

        <div class="row">
            <table class="table" id="datatableform">
                <thead>
                    <tr>
                        <th scope="col">ID phòng</th>
                        <th scope="col">Tên phòng</th>
                        <th scope="col">Tầng</th>
                        <th scope="col">Tòa</th>
                        <th scope="col">Loại phòng</th>
                        <th scope="col">Giá phòng</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.rooms)
                    {
                        <tr>
                            <td>@item.IDRoom</td>
                            <td>@item.Name</td>
                            <td>@item.Floor</td>
                            <td>@item.Building</td>
                            <td>@item.RoomType</td>
                            <td>@item.PriceRoom</td>
                        </tr>

                    }

                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $('#tang').on('change', function (e) {
        var statusval = $(this).val();
        table.column(2).search(statusval).draw();
    })
    $('#toa').on('change', function (e) {
        var statusval = $(this).val();
        table.column(3).search(statusval).draw();
    })
</script>